### ISSUE TITLE
Problem create image

### ISSUE THREAD

**Issue by shudack** [Cypher100/Dynamic-Steam-Signatures#1]
Hi,

I have a problem, when I submit, the picture don't show like attach.
Can you help me please?

Best regards,
Shudack

![2016-03-29 18_27_38-dynamic steam signatures](https://cloud.githubusercontent.com/assets/17851196/14117314/0a23f7da-f5dc-11e5-9c34-ef292dc3111d.png)

**Comment by RenMeow1** [comment]
Are you using Nginx, or Apache?

**Comment by shudack** [comment]
Hi Cypher100,

I use Apache.

**Comment by RenMeow1** [comment]
It may appear that Apache2 is not reading the .htaccess file. Make sure you have AllowOverride All turned on in the Apache2 config

```
<Directory "/var/www">
    AllowOverride All
</Directory>
```

Replace /var/www with the path to where that steam website is located.

**Comment by shudack** [comment]
Hi,

I add AllowOverride All and don't work yet :(

I test deny from all in .htaccess on your project steam folder and work, but with RewriteEngine On
RewriteRule ^images/(._)/(._).png$ /CreateImage.php?skin=$1&username=$2

Image don't show.

**Comment by RenMeow1** [comment]
I made a fresh LAMP setup, and ran 
`a2enmod rewrite`
then added this to the sites config

```
<Directory /var/www/>
    AllowOverride All
</Directory>
```

then created the temp folder inside the steam folder, and 
`chmod 0777 temp`
and of course
`sudo service apache2 restart`

I didn't ran into any problems after that.
