### ISSUE TITLE
Steam ID Not Found

### ISSUE THREAD

**Issue by shudack** [Cypher100/Dynamic-Steam-Signatures#2]
Hi,

I have nginx, php7.0, and url is localhost/steambanner and my nginx rule is rewrite ^/steambanner/steam/images/(.*)/(.*).png$ /steambanner/steam/CreateImage.php?skin$1&username=$2;

I got one image with "Steam ID Not Found.

![2018-09-25 14_35_35-dynamic steam signatures](https://user-images.githubusercontent.com/17851196/46018054-ec00b500-c0d0-11e8-85e3-d3d727fa36b8.png)

Can you help me?

Thanks.

**Comment by RenMeow1** [comment]
"Steam ID Not Found" can occur if it failed to download the profile information or failed to write to the ./steam/temp/ folder. I would first check to see if the temp folder has write permissions set. I would try chmod 777 to the temp folder.

This is a old project, I haven't tested it with PHP 7+, let me know if works with PHP 7.X

**Comment by shudack** [comment]
Hi,

Thanks for help.
Don't work with temp in 777.

![capturar](https://user-images.githubusercontent.com/17851196/46046604-98668980-c119-11e8-9bc4-f72cc80fcb6a.PNG)

Yes i know this is a old project 👍

**Comment by RenMeow1** [comment]
When you attempt to view the signature does any XML file appear in the temp folder? When I have time later today, I'll set it up on my testing server, and take a look. It may require slight adjustments to work on PHP 7.

**Comment by shudack** [comment]
Hi,

I use SSL (HTTPS). Ok, thanks for help.

I read for Curl in SSL, and tell about:
1 Allows curl to make insecure connections, that is curl does not verify the certificate.
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

**Comment by RenMeow1** [comment]
Fixed it, reclone it, and set temp to 777. It should work now.
